# Generated by Django 5.0.6 on 2024-06-09 06:50

import apiapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='icon',
            field=models.ImageField(upload_to=apiapp.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='icon',
            field=models.ImageField(upload_to=apiapp.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='iamge',
            field=models.ImageField(upload_to=apiapp.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='icon',
            field=models.ImageField(upload_to=apiapp.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
