# Generated by Django 5.0.6 on 2024-06-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_education_icon_alter_experiences_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='iamge',
            new_name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='skillused',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiapp.technologies'),
            preserve_default=False,
        ),
    ]
