# Generated by Django 5.0.6 on 2024-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_rename_iamge_projects_image_projects_skillused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skillused',
            field=models.CharField(max_length=100),
        ),
    ]
