# Generated by Django 5.0.6 on 2024-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_alter_projects_skillused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='icon',
            field=models.BinaryField(null=True),
        ),
    ]
