# Generated by Django 5.0.6 on 2024-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_alter_technologies_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
