# Generated by Django 5.0.6 on 2024-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_alter_technologies_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
